# Redis configuration
redis.host=127.0.0.1
redis.port=6379
redis.password=
redis.database=0
redis.timeout=2000
redis.pool.maxTotal=50
redis.pool.maxIdle=20
redis.pool.minIdle=5
redis.pool.maxWaitMillis=3000
